#data type in python 
print(type("hello world"))
print(type('a'))
print(type(1))
print(type(23.45))
print(type(True))
print(type(1+7j))
print(type([1,23,4]))
print(type((1,23,454)))
print(type({'name':"aniket",'age':23}))
